version: '3.8'

services:
  www:
    build: .
    command: python manage.py runserver 0.0.0.0:8005
    ports:
      - "8005:8000"
    depends_on:
      - db
      - redis
    networks:
      - testapp

  db:
    image: postgres:15-alpine
    volumes:
      - testpg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testappdb
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer

  redis:
    image: "redis:3.2-alpine"
    ports:
      - "6380:6379"
    networks:
      - testapp

  rabbitmq:
    image: rabbitmq:3.13.6-alpine
    environment:
      - RABBITMQ_LOG_LEVEL=debug
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - testapp

volumes:
  testpg_data:

networks:
  testapp:
