# Generated by Django 3.2.23 on 2024-10-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Received'), (1, 'Processing'), (2, 'Fulfilled')], default=0, verbose_name='Status')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('completed_dt', models.DateTimeField(auto_now_add=True, verbose_name='Completed Datetime')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Received'), (1, 'Processing'), (2, 'Fulfilled')], default=0, verbose_name='Status')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total items')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('completed_dt', models.DateTimeField(auto_now_add=True, verbose_name='Completed Datetime')),
                ('orders', models.ManyToManyField(related_name='_orders_orderbatch_orders_+', to='orders.Order', verbose_name='Orders')),
            ],
            options={
                'verbose_name': 'Order Batch',
                'verbose_name_plural': 'Order Batches',
            },
        ),
    ]
